name: Simple CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
  workflow_dispatch:

jobs:
  Vechicle-build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Vehicle Service
        run: |
          cd vehicle-service
          javac VehicleService.java
          java VehicleService

  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Driver Service
        run: |
          cd driver-service
          python app.py

  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run Billing Service
        run: |
          cd billing-service
          node server.js

  package:
    needs: [build-java, build-python, build-js]
    runs-on: ubuntu-latest
    steps:
      - name: Combine Artefacts
        run: |
          mkdir deploy
          echo "All Hamilton microservices built and verified successfully!" > deploy/result.txt
          ls deploy
